# .gitlab-ci.yml
image: node:latest # 针对前端，选择合适的node镜像

pages: # 该任务命名必须是pages，是gitlab内部任务
  stage: build
  script:
    - rm -rf public/*
    - mv dist/* public
  artifacts:
    paths:
      - public
  only:
   - master