pages: # 该任务命名必须是pages，是gitlab内部任务
  image: node:8.11.1
  stage: build
  script:
    - "npm install"
    - "npm run build"
    - "cp public/index.html public/404.html"
  cache:
    paths:
    - node_modules/
  artifacts:
    paths:
      - static
  only:
   - master